variables:
  GIT_DEPTH: 1

stages:
  - repoman
  - pkgcheck

repoman:
  image:
    name: aegypius/repoman
    entrypoint: [""]
  stage: repoman
  script:
    - repoman --version
    - FEATURES='-ipc-sandbox -network-sandbox' repoman full -xiIdv

pkgcheck:
  image:
    name: mgorny/gentoo-overlay-ci
    entrypoint: [""]
  stage: pkgcheck
  script:
    - pkgcheck --version
    - pkgcheck scan
